development:
  goal_states: 
    working: 'Working'
    done: 'Done'
    pending: 'Pending'
  exp_type:
    normal: 'Normal'
    useful: 'Useful'
    milestone: 'Milestone'
    impression: 'Impression'
  gender_type:
    'true': 'Male'
    'false': 'Female'
  web_root_url: 'localhost:3000'

production:
  goal_states: 
    working: 'Working'
    done: 'Done'
    pending: 'Pending'
  exp_type:
    normal: 'Normal'
    useful: 'Useful'
    milestone: 'Milestone'
  gender_type:
    'true': 'Male'
    'false': 'Female'
  web_root_url: 'inhertit.iwakela.com'

test: &TEST
  goal_states: 
    working: 'Working'
    done: 'Done'
    pending: 'Pending'
  exp_type:
    normal: 'Normal'
    useful: 'Useful'
    milestone: 'Milestone'
  gender_type:
    'true': 'Male'
    'false': 'Female'
  web_root_url: 'localhost:3000'

cucumber: 
  <<: *TEST
