common: &default_settings
  goal_states: 
    prepare: 'goal.prepare'
    working: 'goal.working'
    pending: 'goal.pending'
    finish: 'goal.finish'
    help: 'goal.needhelp'
  goal_category:
    goal: 'goal'
  exp_type:
    normal: 'Normal'
    useful: 'Useful'
    milestone: 'Milestone'
    impression: 'Impression'
  gender_type:
    'true': 'user.male'
    'false': 'user.female'
  data_number:
    30: 30
    50: 50
    100: 100
    1000: 1000
  web_root_url: 'localhost:3000'

development: 
  <<: *default_settings  

production:
  <<: *default_settings  
  web_root_url: 'inhertit.iwakela.com'

test: 
  <<: *default_settings  

cucumber: 
  <<: *default_settings  
