common: &default_settings
  goal_states: 
    prepare: 'Prepare'
    working: 'Working'
    pending: 'Pending'
    finish: 'Finish'
  goal_category:
    category: 'Category'
    goal: 'Goal'
  exp_type:
    normal: 'Normal'
    useful: 'Useful'
    milestone: 'Milestone'
    impression: 'Impression'
  gender_type:
    'true': 'Male'
    'false': 'Female'
  data_number:
    30: 30
    50: 50
    100: 100
    1000: 1000
  web_root_url: 'localhost:3000'

development: 
  <<: *default_settings  

production:
  <<: *default_settings  
  web_root_url: 'inhertit.iwakela.com'

test: 
  <<: *default_settings  

cucumber: 
  <<: *default_settings  
