--- 
javascripts: 
- base: 
  - jquery
  - application
  - colorPicker
  - facebox
- secondary:
  - experience_timeline
stylesheets: 
- base: 
  - scaffold
  - colorPicker
  - application
  - facebox
