--- 
javascripts: 
- base: 
  - jquery
  - application
  - colorPicker
  - facebox
  - menu
- secondary:
  - experience_timeline
stylesheets: 
- base: 
  - scaffold
  - colorPicker
  - application
  - facebox
  - menu
  - pagination
